spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true

    redis:
      url: ${REDIS_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    context-path: /journal

springdoc:
  swagger-ui:
    path: /doc

api:
  key: ${API_KEY}

secrete:
  key: ${SECRET_KEY}

#server:
#  port: ${SERVER_PORT}