apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008

