apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification-container
          image: ganu853/springboot:notification-service-latest
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: notification-secret

